"""added salary_dt field

Revision ID: 534539fae831
Revises: 7f1dc44f2d6c
Create Date: 2025-10-20 17:14:01.139263

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "534539fae831"
down_revision: Union[str, Sequence[str], None] = "7f1dc44f2d6c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("vacancies", sa.Column("salary_dt", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###

    bind = op.get_bind()
    dialect = bind.dialect.name

    if dialect == "sqlite":
        op.execute("UPDATE vacancies SET salary_dt = datetime('now') WHERE salary > 0;")
    else:
        op.execute(
            "UPDATE vacancies SET salary_dt = CURRENT_TIMESTAMP WHERE salary > 0;"
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vacancies", "salary_dt")
    # ### end Alembic commands ###
